  
name: Main

on: push

jobs:
  repro-docker:
    runs-on: ubuntu-latest
    container: mhart/alpine-node:12
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm i
      - name: Run 
        run: npm run start
        
  repro-cross-platform:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm i
      - name: Run 
        run: npm run start
